enhavo_app_index:
    path:  /
    defaults:
        _controller: Enhavo\Bundle\AppBundle\Controller\AppController:indexAction

enhavo_app_view:
    path:  /view
    defaults:
        _controller: Enhavo\Bundle\AppBundle\Controller\AppController:viewAction