services:
    enhavo_user.event.save_user:
        class: Enhavo\Bundle\UserBundle\EventListener\SaveUserSubscriber
        arguments:
            - '@fos_user.user_manager'
        tags:
            - { name: kernel.event_subscriber }

    Enhavo\Bundle\UserBundle\Form\Type\UserType:
        arguments:
            - '%enhavo_user.model.user.class%'
            - [default]
            - '@security.authorization_checker'
        tags:
            - { name: form.type }

    Enhavo\Bundle\UserBundle\Form\Type\ProfileType:
        arguments:
            - '%enhavo_user.model.user.class%'
        tags:
            - { name: form.type, alias: 'enhavo_user_profile' }

    Enhavo\Bundle\UserBundle\Form\Type\GroupType:
        tags:
            - { name: form.type, alias: 'enhavo_user_group' }
        arguments:
            - '%enhavo_user.model.group.class%'
            - [default]
            - '@security.roles.provider'

    Enhavo\Bundle\UserBundle\Form\Type\ChangeEmailType:
        tags:
            - { name: form.type }
        arguments:
            - '%enhavo_user.model.user.class%'

    security.authentication.voter.group_role_voter:
        class: Enhavo\Bundle\UserBundle\Security\Authentication\Voter\GroupRoleVoter
        public: false
        tags:
            - { name: security.voter }

    enhavo_user.extend_listener.user:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\UserBundle\Entity\User
            - '%enhavo_user.model.user.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_user.extend_listener.group:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\UserBundle\Entity\Group
            - '%enhavo_user.model.group.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Enhavo\Bundle\UserBundle\Menu\UserMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: user_user }

    Enhavo\Bundle\UserBundle\Menu\GroupMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: user_group }

    Enhavo\Bundle\UserBundle\Menu\UserMainMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\ListMenu
        tags:
            - { name: enhavo.menu, alias: user }

    Enhavo\Bundle\UserBundle\Widget\LoginWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: login }

    enhavo_user.controller.security:
        public: true
        class: Enhavo\Bundle\UserBundle\Controller\SecurityController
        arguments:
            - '@view.factory'
            - '@fos_rest.view_handler'
            - '@security.csrf.token_manager'
        calls:
            - [setContainer, ['@service_container']]

    enhavo_user.viewer.confirm:
        class: Enhavo\Bundle\UserBundle\Viewer\ConfirmViewer
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: confirm }
