services:
    enhavo_app.action_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'Action'

    enhavo_app.action_manager:
        class: Enhavo\Bundle\AppBundle\Action\ActionManager
        arguments:
            - '@enhavo_app.action_collector'
            - '@security.authorization_checker'

    Enhavo\Bundle\AppBundle\Action\AbstractActionType:
        abstract: true
        arguments:
            - '@translator'
        tags:
            - { name: enhavo.action, alias: create }

    Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        abstract: true
        arguments:
            - '@router'
        tags:
            - { name: enhavo.action, alias: create }

    Enhavo\Bundle\AppBundle\Action\Type\CreateActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: create }

    Enhavo\Bundle\AppBundle\Action\Type\DownloadActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: download }
              
    Enhavo\Bundle\AppBundle\Action\Type\DeleteActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: delete }

    Enhavo\Bundle\AppBundle\Action\Type\CloseActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        public: true
        tags:
            - { name: enhavo.action, alias: close }

    Enhavo\Bundle\AppBundle\Action\Type\PreviewActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: preview }

    Enhavo\Bundle\AppBundle\Action\Type\SaveActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: save }

    Enhavo\Bundle\AppBundle\Action\Type\DuplicateActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: duplicate }