services:
    Enhavo\Bundle\AppBundle\Controller\LoginController:
        arguments:
            - '@router'
            - '%enhavo_app.login.route%'
            - '%enhavo_app.login.route_parameters%'
        tags:
            - { name: controller.service_arguments }

    Enhavo\Bundle\AppBundle\Controller\MainController:
        arguments:
            - '@enhavo_app.menu.manager'
        tags:
            - { name: controller.service_arguments }