services:
    Enhavo\Bundle\AppBundle\Twig\PaginationRender:
        arguments:
            - 'EnhavoAppBundle:View:pagination.html.twig'
        calls:
            - [ setEngine, ['@templating']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\AdminAsset:
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\Branding:
        arguments:
            - '%enhavo_app.branding%'
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\Template:
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\UrlBeautifier:
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\Form:
        arguments:
            - '%enhavo_app.form_themes%'
            - '@enhavo_form.error.error.resolver'
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\Slugify:
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\SplObject:
        tags:
            - { name: twig.extension }