services:
    enhavo_app.viewer_collector:
        public: true
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'

    view.factory:
        public: true
        class: Enhavo\Bundle\AppBundle\Viewer\ViewFactory
        arguments:
            - '@service_container'
            - '@enhavo_app.viewer_collector'

    Enhavo\Bundle\AppBundle\Viewer\ViewerUtil:
        arguments:
            - '@sylius.resource_controller.parameters_parser'
            - 'Enhavo\Bundle\AppBundle\Controller\RequestConfiguration'
            - '%sylius.resource.settings%'
            - '@router'

    Enhavo\Bundle\AppBundle\Viewer\Viewer\IndexViewer:
        parent: Enhavo\Bundle\AppBundle\Viewer\Viewer\AppViewer
        public: true
        arguments:
            - '@enhavo_app.action_manager'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: index }

    Enhavo\Bundle\AppBundle\Viewer\Viewer\CreateViewer:
        public: true
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@Enhavo\Bundle\AppBundle\Viewer\ViewerUtil'
            - '%enhavo_app.form_themes%'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: create }

    Enhavo\Bundle\AppBundle\Viewer\Viewer\UpdateViewer:
        public: true
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@Enhavo\Bundle\AppBundle\Viewer\ViewerUtil'
            - '%enhavo_app.form_themes%'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: update }

    Enhavo\Bundle\AppBundle\Viewer\Viewer\AppViewer:
        public: true
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@Enhavo\Bundle\AppBundle\Viewer\ViewerUtil'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: app }

    Enhavo\Bundle\AppBundle\Viewer\Viewer\BaseViewer:
        public: true
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@Enhavo\Bundle\AppBundle\Viewer\ViewerUtil'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: base }

    Enhavo\Bundle\AppBundle\Viewer\Viewer\TableViewer:
        public: true
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@Enhavo\Bundle\AppBundle\Viewer\ViewerUtil'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: table }

    Enhavo\Bundle\AppBundle\Viewer\Viewer\ListViewer:
        public: true
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@Enhavo\Bundle\AppBundle\Viewer\ViewerUtil'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: list }

    Enhavo\Bundle\AppBundle\Viewer\Viewer\PreviewViewer:
        public: true
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@Enhavo\Bundle\AppBundle\Viewer\ViewerUtil'
            - '@enhavo_app.preview.strategy_resolver'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: preview }

    Enhavo\Bundle\AppBundle\Viewer\PreviewViewHandler: