framework:
    translator: { fallback: "%locale%" }
    validation:
        enabled: true
    session:
        cookie_lifetime: 25920000
    templating:
        engines: twig

doctrine:
    dbal:
        mapping_types:
            enum: string
            json: string
            json_array: string

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            sluggable: true
            timestampable: true

sylius_resource:
    authorization_checker: enhavo_app.security.default_authorization_checker

enhavo_assets:
    require_js:
        paths:
            app:
                location: /bundles/enhavoapp/js/app

jms_serializer:
    metadata:
        auto_detection: false

enhavo_app:
    apps:
      - 'app/Menu'
      - 'app/ConditionType'
      - 'app/Adapter/DynamicForm/EnhavoAdapter'
    form_themes:
      - 'EnhavoAppBundle:Form:fields.html.twig'